#FROM pytorch/pytorch:0.4_cuda9_cudnn7
#FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime
#FROM pytorch/pytorch:1.0-cuda10.0-cudnn7-runtime
FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime

# make pip3 command available
RUN ln -s /opt/conda/bin/pip /usr/bin/pip3 
