FROM seunglab/kaffe:pznet

LABEL maintainer="Jingpeng Wu"\
    email="jingpeng@princeton.edu"

ENV PYTHONPATH /opt/znnphi_interface/code/znet/src/python:$PYTHONPATH
RUN apt-get update \
    && apt-get install -y python3-pip \
    && ln -s /usr/bin/pip3 /usr/bin/pip
